Adding default email template
Volontaria/API-Volontaria pull request #265
Opened 2020-10-17 21:06 UTC by Vardane

| Q                                          | R
| ------------------------------------------ | -------------------------------------------
| Type of contribution ?                     | [Enhancement]
| Tickets (_issues_) concerned               | [246]

---

##### What have you changed ?
- send_email_confirmation function and send_email_cancellation_emergency in Participation class
- added static files

##### How did you change it ?
- added feature allowing using a default email template

##### Is there a special consideration?
work in progress; not ready to merge; only pushed at this stage to allow tracking of progress

Verification :
 -  [x ] My branch name respect the standard defined in `CONTRIBUTING.md`
 -  [ ] All my commits respect the standard defined in `CONTRIBUTING.md`
 -  [ ] This Pull-Request fully meets the requirements defined in the issue
 -  [ ] I added or modified the attached tests
 -  [ ] I added or modified the documentation

2020-10-28 02:06 UTC, Vardane commented
@RignonNoel The test test_send_email_confirmation in test_view_participations returns an error. Message says that 3 emails are send, while I was expecting (and testing for) one (I assume a single confirmation is sent to user).
I wonder: are 3 emails actually sent every time a new position is created? Or is it because the testing context keeps in memory positions created when other test functions where run in the same series of tests? Or some other reason?

Error message:

Traceback (most recent call last):
  File "/home/vardane/Documents/api_volontaria/API-Volontaria/api_volontaria/apps/volunteer/tests/test_view_participations.py", line 417, in test_send_email_confirmation
    self.assertEqual(len(mail.outbox), 1)
AssertionError: 3 != 1

2020-12-14 23:44 UTC, RignonNoel requested changes
Think to add all the generated static to the `.gitignore`

2020-12-14 23:44 UTC, RignonNoel commented on .vscode/settings.json
> +}
`.vscode` -> should be added to `.gitignore`

2020-12-14 23:44 UTC, RignonNoel commented on api_volontaria/apps/user/tests/tests_view_users.py
> +from api_volontaria.apps.log_management.models import EmailLog
You just added this line but it's not used so you can remove it

2020-12-14 23:44 UTC, RignonNoel commented on api_volontaria/apps/volunteer/models.py
> +
Code should not be commented but removed

2020-12-14 23:44 UTC, RignonNoel commented on api_volontaria/apps/volunteer/tests/test_view_participations.py
> +        # 1. email sent?
Les petit commentaires comme celui-ci peuvent etre enlever maintenant

2020-12-14 23:44 UTC, RignonNoel commented on api_volontaria/apps/volunteer/tests/test_view_participations.py
> +        # 2.a and 2.b: proper template?
Idem

2020-12-14 23:44 UTC, RignonNoel commented on api_volontaria/apps/volunteer/tests/test_view_participations.py
> +        # 1. email sent?
Idem

2020-12-14 23:44 UTC, RignonNoel commented on api_volontaria/apps/volunteer/tests/test_view_participations.py
> +        # 2.a and 2.b: proper template?
Idem

2020-12-14 23:44 UTC, RignonNoel commented on api_volontaria/settings.py
> +#     STATIC_ROOT = 'static/'
Code should not be commented, if needed you can remove it
PS: The old comment was cool to have in the settings in think

2020-12-14 23:44 UTC, RignonNoel commented on api_volontaria/settings.py
> +#     )
Remove commented code

2020-12-30 16:07 UTC, merged